name: smart_books
description: "財Tech - シンプルで使いやすい会計アプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI関連
  cupertino_icons: ^1.0.6
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0
  animations: ^2.0.8
  table_calendar: ^3.0.9
  avatar_glow: ^2.0.2 # 追加: 音声録音時の視覚的フィードバック用

  # 状態管理
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4

  # API/ネットワーク
  dio: ^5.3.3
  connectivity_plus: ^5.0.1

  # ストレージ
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # ファイル操作
  image_picker: ^1.0.4
  # file_picker: ^5.2.10
  camera: ^0.10.5+5
  url_launcher: ^6.2.1

  # オーディオ
  audioplayers: ^5.2.1
  just_audio: ^0.9.35
  speech_to_text: ^6.3.0 # 追加: 音声認識用
  record: ^4.4.4 # 追加: 音声録音用
  permission_handler: ^10.4.3 # 追加: マイク権限管理用

  # 通知
  flutter_local_notifications: ^15.1.2
  timezone: ^0.9.2

  # その他のユーティリティ
  intl: ^0.19.0
  uuid: ^4.1.0
  flutter_dotenv: ^5.1.0
  postgres: ^2.6.2
  dotted_border: ^2.0.0
  flutter_sound: ^9.2.13
  lottie: ^2.3.2
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
    - assets/animations/
    - .env
